import Head from "next/head";
import { ReactElement } from "react";
import { NextPageWithLayout } from "./_app";
import Navbar from "../components/Navbar";

const Home: NextPageWithLayout = (props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <Navbar />
      {page}
    </>
  );
};

export async function getServerSideProps(context) {
  try {
    // const response = await fetch(`https://gorest.co.in/public-api/products`);
    // console.log(response)
    // const result = await response.json();
    return { props: { productData: [] } };
  } catch (e) {
    console.log("e ===", e);
  }
}

export default Home;
